[package]
name = "dargo"
version = "0.1.0"
authors = ["DCjanus <dcjanus@dcjanus.com>"]
edition = "2018"

[dependencies]
cargo = "0.35.0"
failure = "0.1.5"
toml_edit = "0.1.3"
structopt = "0.2.15"
log = "0.4.6"
flexi_logger = "0.13.1"
file = "1.1.2"
semver = "0.9.0"
colored = "1.8.0"
tabwriter = "1.1.0"
